apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: clientvault
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/client_vault"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"


