apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientvault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientvault
  template:
    metadata:
      labels:
        app: clientvault
    spec:
      containers:
        - name: clientvault-container
          image: durksie/clientvault-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret